[project]
name = "myblog-scripts"
version = "0.1.0"
description = "A static blog built with Zola"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "brotli>=1.2.0",
    "fonttools>=4.61.1",
    "niquests>=3.17.0",
]

# 新增下面这个部分
[dependency-groups]
local = [
    "imagekitio>=5.1.0",
    "socksio>=1.0.0",
]

[tool.ty.environment]
root = ["."]
python = "./.venv"