name: Build and Deploy Zola

on:
  push:
    branches: ["master"]
    paths-ignore:
      - "README.md"
      - ".vscode/**"
      - ".gitignore"
      - "local_preview.sh"
      - "upload_cache.json" # 这是你上传脚本的缓存，不影响站点构建
      - "upload_img.py"
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
          submodules: recursive

      - name: Setup uv
        id: setup-uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: 3.14

      - name: Run Pre-build Scripts
        run: |
          uv sync --no-default-groups
          uv run python optimize_fonts.py
          uv run python sync_data.py
          find content -name "*.md" -exec sed -i 's|../../static/images/|/images/|g' {} +

      - name: Install Zola
        uses: taiki-e/install-action@v2
        with:
          tool: zola@0.22.1

      - name: Build Zola
        run: zola build
      - name: Replace JS Library & Fix Sitemap
        run: |
          wget -O public/js/lightense.min.js https://cdn.jsdelivr.net/npm/@kaesinol/lightense-images@latest/dist/lightense.min.js

          tmp=$(mktemp)

          curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/kaixinol/tools/git/trees/main?recursive=1" \
          | jq -r '.tree[] | select(.path | endswith("index.html")) | .path' \
          | sed 's#index.html$##' \
          | sed 's#^#/tools/#' \
          | sed 's#//#/#g' \
          | sort -u \
          | sed 's#^#<url><loc>#; s#$#</loc></url>#' > "$tmp"

          # 檢查內容並插入
          if [ -s "$tmp" ]; then
            sed "/<\/urlset>/e cat $tmp" public/sitemap.xml > public/sitemap.new.xml
            mv public/sitemap.new.xml public/sitemap.xml
          fi
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
