name: Build and Deploy Zola

on:
  push:
    branches: ["master"]
    paths-ignore:
      - "README.md"
      - ".vscode/**"
      - ".gitignore"
      - "local_preview.sh"
      - "upload_cache.json" # 这是你上传脚本的缓存，不影响站点构建
      - "upload_img.py"
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
          submodules: recursive

      - name: Setup uv
        id: setup-uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: 3.14

      - name: Run Pre-build Scripts
        run: |
          uv sync --no-default-groups
          uv run python optimize_fonts.py
          uv run python upload_img.py
          uv run python sync_data.py

      - name: Install Zola
        uses: taiki-e/install-action@v2
        with:
          tool: zola@0.22.1

      - name: Build Zola
        run: zola build
      - name: Replace JS Library & Fix Sitemap
        run: |
          wget -O public/js/lightense.min.js https://cdn.jsdelivr.net/npm/@kaesinol/lightense-images@latest/dist/lightense.min.js
          sed -E -i 's/::selection\s*\{[^}]*\}//g' public/main.css
          tmp_file=$(mktemp)
          uv run python add_tools.py > "$tmp_file"

          if [ -s "$tmp_file" ]; then
            awk '
            /<\/urlset>/ {
              while ((getline line < "'"$tmp_file"'") > 0) print line
            }
            { print }
            ' public/sitemap.xml > public/sitemap.xml.tmp && \
            mv public/sitemap.xml.tmp public/sitemap.xml
          fi

          rm -f "$tmp_file"
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
